[workspace]
resolver = "2"
members = [ 
    "platform/nemu", 
    "bin/dummy", 
    "macros", 
]

[workspace.dependencies]
embedded-hal = "1.0.0"
embedded-alloc = "0.6"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
