[workspace]
resolver = "2"
members = [
    "macros",

    "platform/build-helper",
    "platform/nemu",
    "platform/qemu",
    "platform/runtime",

    "bin/dummy",
    "bin/hello_world",
    "bin/alloc",

    "bin/vector",
]

[workspace.dependencies]
embedded-hal = "1.0.0"
embedded-alloc = "0.6"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
