[workspace]
resolver = "2"
members = [
    "macros",
    "platform/nemu",
    "platform/runtime",
    
    "bin/dummy",
    "bin/alloc",
]

[workspace.dependencies]
embedded-hal = "1.0.0"
embedded-alloc = "0.6"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
