[package]
name = "mnist"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = [ "wenjiu <27843087979@qq.com>" ]

[build-dependencies]
build-helper = { path = "../../../platform/build-helper" }

[dependencies]
macros = { path = "../../../macros" }
runtime = { path = "../../../platform/runtime" }
embedded-hal = { workspace = true }
embedded-alloc = { workspace = true }

[dev-dependencies]
fltk = "1.4"
egui = "0.33.2"
eframe = "0.33.2"
winit = "0.30.12"
