[package]
name = "matrix"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = [ "wenjiu <27843087979@qq.com>" ]

[build-dependencies]
runtime = { path = "../../platform/runtime" }

[dependencies]
macros = { path = "../../macros" }
nemu_runtime = { path = "../../platform/nemu" }
embedded-hal = { workspace = true }
embedded-alloc = { workspace = true }
