[package]
name = "graphic"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = [ "wenjiu <27843087979@qq.com>" ]

[package.metadata.requirement.io]
graphic = true

[build-dependencies]
build-helper = { path = "../../../platform/build-helper" }

[package.metadata.test]
involved = true

[dependencies]
macros = { path = "../../../macros" }
runtime = { path = "../../../platform/runtime" }
embedded-hal = { workspace = true }
embedded-alloc = { workspace = true }
